### ISSUE TITLE
Known issue with deadlock with mass additions

### ISSUE THREAD

**Issue by gotzmann** [bdasgupta02/dynamap#1]
Hey, found your awesome lib and thinking about using it within one of my project, but this thing stops me:

- Known issue with deadlock with mass additions

Are there plans to fix this? Otherwise looks well implemented and easy to use, but I need 100% robust lib for multi-threaded server application.

**Comment by bdasgupta02** [comment]
Hey, unfortunately there are no active plans to maintain this, or fix some underlying issues.

I recommend using the hash map from the standard library meanwhile!

Thanks for looking into the project though!

**Comment by bdasgupta02** [comment]
Or perhaps:
https://github.com/kshk123/hashMap

or similar alternatives for thread safety

**Comment by gotzmann** [comment]
Thanks for quick reply and suggestions! Seen those, not so attractive :)

Going to start with combo of `std::shared_mutex` and `std::unordered_map`.
